sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: li594438
  alioss:
    bucket-name: web-tlias-lizewei
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCKvqEaYzrWVjGzXeh1
    access-key-secret: vBdoY6PQ8gDtVDALy9GHiUag6wcwon

  redis:
    host: localhost
    port: 6379
    auth: 'li594438'
    database: 0

  wechat:
    appid: wx8696c7b690f9ea2e
    secret: 2ecfde626223f769d00e7b508a26f311
