sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: li594438
  alioss:
    bucket-name: web-tlias-lizewei
    endpoint: oss-cn-hangzhou.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    auth: 'li594438'
    database: 0